# ░░░░░░░░░░░░░░░░░
# ░█░█░█▀▀░█▀▀░▀█▀░
# ░░█░░█▀▀░█▀▀░░█░░
# ░░▀░░▀▀▀░▀▀▀░░▀░░
# ░░░░░░░░░░░░░░░░░
# 
## CONFIGURATION FILE
## ------------------

AUR_BASE_URL="https://aur.archlinux.org"
PACMAN_BIN=/usr/bin/pacman
SUDO_BIN=/usr/bin/sudo
CACHE_DIR=/home/scorpio/.cache/yeet/
FILE_MANAGER=/usr/bin/yazi
PRINT_LOGO=true
